# Generated by Django 3.1.8 on 2022-04-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip2Asn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.TextField(blank=True, null=True)),
                ('range_end', models.TextField(blank=True, null=True)),
                ('AS_number', models.IntegerField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('AS_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ip2asn',
                'managed': False,
            },
        ),
    ]
